# Documentação: https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-rabbitmq/
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://guest:guest@localhost:5672/"